/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitesIndexRouteImport } from './routes/sites/index'
import { Route as GatePasswordRouteImport } from './routes/gate/password'
import { Route as GateLoginRouteImport } from './routes/gate/login'
import { Route as GateDeniedRouteImport } from './routes/gate/denied'
import { Route as SitesSiteIdIndexRouteImport } from './routes/sites/$siteId/index'
import { Route as SitesSiteIdSettingsRouteImport } from './routes/sites/$siteId/settings'
import { Route as SitesSiteIdDeployRouteImport } from './routes/sites/$siteId/deploy'
import { Route as SitesSiteIdAnalyticsRouteImport } from './routes/sites/$siteId/analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIndexRoute = SitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => rootRouteImport,
} as any)
const GatePasswordRoute = GatePasswordRouteImport.update({
  id: '/gate/password',
  path: '/gate/password',
  getParentRoute: () => rootRouteImport,
} as any)
const GateLoginRoute = GateLoginRouteImport.update({
  id: '/gate/login',
  path: '/gate/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GateDeniedRoute = GateDeniedRouteImport.update({
  id: '/gate/denied',
  path: '/gate/denied',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdIndexRoute = SitesSiteIdIndexRouteImport.update({
  id: '/sites/$siteId/',
  path: '/sites/$siteId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdSettingsRoute = SitesSiteIdSettingsRouteImport.update({
  id: '/sites/$siteId/settings',
  path: '/sites/$siteId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdDeployRoute = SitesSiteIdDeployRouteImport.update({
  id: '/sites/$siteId/deploy',
  path: '/sites/$siteId/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdAnalyticsRoute = SitesSiteIdAnalyticsRouteImport.update({
  id: '/sites/$siteId/analytics',
  path: '/sites/$siteId/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/gate/denied': typeof GateDeniedRoute
  '/gate/login': typeof GateLoginRoute
  '/gate/password': typeof GatePasswordRoute
  '/sites': typeof SitesIndexRoute
  '/sites/$siteId/analytics': typeof SitesSiteIdAnalyticsRoute
  '/sites/$siteId/deploy': typeof SitesSiteIdDeployRoute
  '/sites/$siteId/settings': typeof SitesSiteIdSettingsRoute
  '/sites/$siteId': typeof SitesSiteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/gate/denied': typeof GateDeniedRoute
  '/gate/login': typeof GateLoginRoute
  '/gate/password': typeof GatePasswordRoute
  '/sites': typeof SitesIndexRoute
  '/sites/$siteId/analytics': typeof SitesSiteIdAnalyticsRoute
  '/sites/$siteId/deploy': typeof SitesSiteIdDeployRoute
  '/sites/$siteId/settings': typeof SitesSiteIdSettingsRoute
  '/sites/$siteId': typeof SitesSiteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/gate/denied': typeof GateDeniedRoute
  '/gate/login': typeof GateLoginRoute
  '/gate/password': typeof GatePasswordRoute
  '/sites/': typeof SitesIndexRoute
  '/sites/$siteId/analytics': typeof SitesSiteIdAnalyticsRoute
  '/sites/$siteId/deploy': typeof SitesSiteIdDeployRoute
  '/sites/$siteId/settings': typeof SitesSiteIdSettingsRoute
  '/sites/$siteId/': typeof SitesSiteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/gate/denied'
    | '/gate/login'
    | '/gate/password'
    | '/sites'
    | '/sites/$siteId/analytics'
    | '/sites/$siteId/deploy'
    | '/sites/$siteId/settings'
    | '/sites/$siteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/gate/denied'
    | '/gate/login'
    | '/gate/password'
    | '/sites'
    | '/sites/$siteId/analytics'
    | '/sites/$siteId/deploy'
    | '/sites/$siteId/settings'
    | '/sites/$siteId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/gate/denied'
    | '/gate/login'
    | '/gate/password'
    | '/sites/'
    | '/sites/$siteId/analytics'
    | '/sites/$siteId/deploy'
    | '/sites/$siteId/settings'
    | '/sites/$siteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  GateDeniedRoute: typeof GateDeniedRoute
  GateLoginRoute: typeof GateLoginRoute
  GatePasswordRoute: typeof GatePasswordRoute
  SitesIndexRoute: typeof SitesIndexRoute
  SitesSiteIdAnalyticsRoute: typeof SitesSiteIdAnalyticsRoute
  SitesSiteIdDeployRoute: typeof SitesSiteIdDeployRoute
  SitesSiteIdSettingsRoute: typeof SitesSiteIdSettingsRoute
  SitesSiteIdIndexRoute: typeof SitesSiteIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/': {
      id: '/sites/'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate/password': {
      id: '/gate/password'
      path: '/gate/password'
      fullPath: '/gate/password'
      preLoaderRoute: typeof GatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate/login': {
      id: '/gate/login'
      path: '/gate/login'
      fullPath: '/gate/login'
      preLoaderRoute: typeof GateLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate/denied': {
      id: '/gate/denied'
      path: '/gate/denied'
      fullPath: '/gate/denied'
      preLoaderRoute: typeof GateDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId/': {
      id: '/sites/$siteId/'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof SitesSiteIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId/settings': {
      id: '/sites/$siteId/settings'
      path: '/sites/$siteId/settings'
      fullPath: '/sites/$siteId/settings'
      preLoaderRoute: typeof SitesSiteIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId/deploy': {
      id: '/sites/$siteId/deploy'
      path: '/sites/$siteId/deploy'
      fullPath: '/sites/$siteId/deploy'
      preLoaderRoute: typeof SitesSiteIdDeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId/analytics': {
      id: '/sites/$siteId/analytics'
      path: '/sites/$siteId/analytics'
      fullPath: '/sites/$siteId/analytics'
      preLoaderRoute: typeof SitesSiteIdAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  GateDeniedRoute: GateDeniedRoute,
  GateLoginRoute: GateLoginRoute,
  GatePasswordRoute: GatePasswordRoute,
  SitesIndexRoute: SitesIndexRoute,
  SitesSiteIdAnalyticsRoute: SitesSiteIdAnalyticsRoute,
  SitesSiteIdDeployRoute: SitesSiteIdDeployRoute,
  SitesSiteIdSettingsRoute: SitesSiteIdSettingsRoute,
  SitesSiteIdIndexRoute: SitesSiteIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
