/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitesIndexRouteImport } from './routes/sites/index'
import { Route as SitesSiteIdRouteImport } from './routes/sites/$siteId'
import { Route as ViewSlugSplatRouteImport } from './routes/view/$slug/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIndexRoute = SitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdRoute = SitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewSlugSplatRoute = ViewSlugSplatRouteImport.update({
  id: '/view/$slug/$',
  path: '/view/$slug/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites': typeof SitesIndexRoute
  '/view/$slug/$': typeof ViewSlugSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites': typeof SitesIndexRoute
  '/view/$slug/$': typeof ViewSlugSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/': typeof SitesIndexRoute
  '/view/$slug/$': typeof ViewSlugSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sites/$siteId' | '/sites' | '/view/$slug/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sites/$siteId' | '/sites' | '/view/$slug/$'
  id: '__root__' | '/' | '/sites/$siteId' | '/sites/' | '/view/$slug/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitesSiteIdRoute: typeof SitesSiteIdRoute
  SitesIndexRoute: typeof SitesIndexRoute
  ViewSlugSplatRoute: typeof ViewSlugSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/': {
      id: '/sites/'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId': {
      id: '/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof SitesSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$slug/$': {
      id: '/view/$slug/$'
      path: '/view/$slug/$'
      fullPath: '/view/$slug/$'
      preLoaderRoute: typeof ViewSlugSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitesSiteIdRoute: SitesSiteIdRoute,
  SitesIndexRoute: SitesIndexRoute,
  ViewSlugSplatRoute: ViewSlugSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
